apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: csuos-infra
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-secret: "admin"
spec:
  rules:
  - host: vault.csuos.ml
    http:
      paths:
        - backend:
            serviceName: vault-svc
            servicePort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: vault-svc
  namespace: csuos-infra
spec:
  ports:
  - port: 8200
    targetPort: 8200
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vault-svc
  namespace: csuos-infra
subsets:
  - addresses:
    - ip: 192.168.0.240
    ports:
    - port: 8200