apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
spec:
  rules:
  - host: argo.csuos.ml
    http:
      paths:
        - backend:
            serviceName: argocd-server
            servicePort: 80
