apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nera-ingress
  namespace: apps
spec:
  rules:
  - host: nera.csuos.ml
    http:
      paths:
        - backend:
            serviceName: nera-svc
            servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nera-svc
  namespace: apps
spec:
  selector:
    app: nera
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nera-deployment
  namespace: apps
spec:
  selector:
    matchLabels:
      app: nera
  template:
    metadata:
      labels:
        app: nera
    spec:
      containers:
      - name: nera
        image: csuos/nera:sha-8be2426
        env:
          - name: VAULT_TOKEN
            value: s.5XIRXSCbCF808CmkRaPXDzk4
          - name: VAULT_ADDR
            value: http://vault-svc.csuos-infra.svc:8200
          - name: VAULT_PATH
            value: /csuos/nera
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
