apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rabums-ingress
  namespace: apps
spec:
  rules:
  - host: rabums.csuos.ml
    http:
      paths:
        - backend:
            serviceName: rabums-svc
            servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rabums-svc
  namespace: apps
spec:
  selector:
    app: rabums
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabums-deployment
  namespace: apps
spec:
  selector:
    matchLabels:
      app: rabums
  template:
    metadata:
      labels:
        app: rabums
    spec:
      containers:
      - name: rabums
        image: csuos/rabums:0.1.2
        imagePullPolicy: Always
        env:
          - name: VAULT_TOKEN
            value: s.5XIRXSCbCF808CmkRaPXDzk4
          - name: VAULT_ADDRESS
            value: http://vault-svc.csuos-infra.svc:8200
          - name: VAULT_PATH
            value: /csuos/rabums
        resources:
          limits:
            memory: "64Mi"
            cpu: "10m"
        ports:
        - containerPort: 8080
