version : '3'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        #environment:
        #    MYSQL_ROOT_PASSWORD: ***
        #    MYSQL_DATABASE: default_schema
        volumes:
        - ./data:/var/lib/mysql
        ports:
        - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
        - "10080:80"